gems:
  - jekyll-paginate
  - bourbon
  - jekyll-gist
  - jekyll-sitemap

# SEO settings
title: "Script"
title2: "Ops" 
description: "IT tools for our robotic overlords"
keywords: "powershell, blog, admin, devops, automation, script"
url: https://scriptops.com


google_analytics: UA-79423450-2
repo: http://github.com/jbilinski
disqus_shortname: "scriptops"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
kramdown:
  input: GFM
highlighter : rouge

source: ./
destination: ./_site


# Author settings
author:
  name     : "Jan Bilinski"
  job      : "IT Infrastructure Engineer"
  bio      : "Disruptive technologies are automating my work and obsoleting decades of knowledge! --thanks, let me help with that."
  email    : jbilinski+blog@gmail.com
  url      : https://about.me/jbilinski
  github   : http://github.com/jbilinski
  twitter  : http://twitter.com/ScriptOps
  linkedin : http://linkedin.com/in/jbilinski
  thumb    : http://gravatar.com/avatar/7ef7f59e6bfa3188f7999841f7382348
  # facebook : https://www.facebook.com/profile.php?id=123456789
# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@ScriptOps"

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
encoding: utf-8
