gems:
  - jekyll-paginate
  - bourbon

# SEO settings
title: "river"
title2: "live" 
description: "IT Tools"
keywords: "powershell, blog, admin, devops, automation, script"
url: https://riverlive.com


google_analytics: UA-79423450-1
repo: http://github.com/jbilinski
disqus_shortname: "riverlive"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site


# Author settings
author:
  name     : "Jamie Bilinski"
  job      : "IT Infrastructure Engineer"
  bio      : "And now I shall replace myself with a small PowerShell script."
  email    : jbilinski+blog@gmail.com
  url      : https://about.me/jbilinski
  github   : http://github.com/jbilinski
  twitter  : http://twitter.com/GravityNoob
  linkedin : http://linkedin.com/in/jbilinski
  #  thumb    : /images/author.jpg
  # facebook : https://www.facebook.com/profile.php?id=123456789
# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@GravityNoob"

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
encoding: utf-8
